import { useRetainedDraft } from '../workspace/DraftOwner'
import { useEffect, useRef, useState } from 'react'
import type { OpenProject } from '../../../../shared/projects'
import type { SourceMetadata, SourceRecord, SourcesView, SourceImportPreview, SourceImportChoice, SourceChangeInput, BibliographyFormat } from '../../../../shared/sources'
import { SOURCE_TYPES } from '../../../../shared/sources'

const blank = (): SourceMetadata => ({type:'article-journal',title:'',author:[],issued:'',containerTitle:'',publisher:'',edition:'',volume:'',issue:'',page:'',DOI:'',URL:'',ISBN:'',ISSN:''})
const scope = (project:OpenProject) => ({projectId:project.projectId,workspaceId:project.workspaceId})
const creators = (metadata:SourceMetadata):string => metadata.author.map(a=>a.literal || `${a.family}${a.given?`, ${a.given}`:''}`).join('; ')
const parseCreators = (text:string):SourceMetadata['author'] => text.split(';').map(s=>s.trim()).filter(Boolean).map(s=>{if(!s.includes(','))return {family:'',given:'',literal:s};const [family,...given]=s.split(',');return {family:family.trim(),given:given.join(',').trim(),literal:''}})

export default function SourcesPanel({project,focusSourceId,disabled,readOnly,onCommitted,onInspect}:{project:OpenProject;focusSourceId:string|null;disabled:boolean;readOnly:boolean;onCommitted:()=>Promise<void>;onInspect:(sourceId:string)=>void}):React.JSX.Element {
  const panel = useRef<HTMLElement>(null), focusedRequest = useRef<string | null>(null), saveTask = useRef<Promise<boolean> | null>(null)
  const [view,setView]=useState<SourcesView|null>(null),[selected,setSelected]=useState<string|null>(null)
  const [draft,setDraft]=useState<SourceMetadata>(blank),[creatorText,setCreatorText]=useState(''),[verified,setVerified]=useState(false),[linked,setLinked]=useState<string[]>([])
  const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  const [preview,setPreview]=useState<SourceImportPreview|null>(null),[choices,setChoices]=useState<SourceImportChoice[]>([]),[exportFormat,setExportFormat]=useState<BibliographyFormat>('csl-json'),[exportSelection,setExportSelection]=useState<string[]>([]),[exportLosses,setExportLosses]=useState<string[]>([]),[mergeTarget,setMergeTarget]=useState('')
  const [attachmentProgress,setAttachmentProgress]=useState<{transferred:number;total:number}|null>(null),attachmentOperation=useRef<string|null>(null)
  const pending=useRef<SourceChangeInput|null>(null),pendingImport=useRef<string|null>(null),latest=useRef({selected:null as string|null,draft:blank(),verified:false,linked:[] as string[],dirty:false,view:null as SourcesView|null})
  latest.current={selected,draft:{...draft,author:parseCreators(creatorText)},verified,linked,dirty,view}
  useEffect(()=>{let active=true;void window.collie.readSources(scope(project)).then(result=>{if(!active)return;if(result.ok)setView(result.value);else setError(result.error.message)});return()=>{active=false}},[project.projectId,project.workspaceId,project.headCommitId])
  useEffect(()=>window.collie.onSourceProgress(progress=>{if(progress.operationId===attachmentOperation.current)setAttachmentProgress({transferred:progress.transferred,total:progress.total})}),[])
  function change(next:SourceMetadata,authors=creatorText):void {setDraft(next);setCreatorText(authors);setDirty(true);pending.current=null}
  function choose(row:SourceRecord|null):void {if(dirty)return;setSelected(row?.id??null);setDraft(row?.metadata??blank());setCreatorText(row?creators(row.metadata):'');setVerified(row?.verified??false);setLinked(row?.documentIds??[]);setMergeTarget('');setError('');setMessage('')}
  useEffect(() => {
    if (!focusSourceId) { focusedRequest.current = null; return }
    if (!view || dirty || focusedRequest.current === focusSourceId) return
    const target = view.sources.find(source => source.id === focusSourceId)
    if (target) { focusedRequest.current = focusSourceId; choose(target) }
    else setError('The requested source is no longer available.')
  }, [focusSourceId, view?.sources])
  async function save(): Promise<boolean> {
    if (saveTask.current) return saveTask.current
    const task = saveOnce(); saveTask.current = task
    try { return await task } finally { if (saveTask.current === task) saveTask.current = null }
  }

  async function saveOnce():Promise<boolean>{
    const state=latest.current;if(!state.dirty&&!pending.current)return true
    const current=state.view?.sources.find(s=>s.id===state.selected)
    const input=pending.current??{...scope(project),operationId:crypto.randomUUID(),change:current?{type:'update' as const,id:current.id,expectedRevisionId:current.revisionId,metadata:state.draft,verified:state.verified,documentIds:state.linked}:{type:'create' as const,id:crypto.randomUUID(),metadata:state.draft,verified:state.verified,documentIds:state.linked}}
    pending.current=input;setBusy(true);setError('')
    try {const result=await window.collie.changeSource(input);if(!result.ok){setError(result.error.message);if(result.error.code!=='UNAVAILABLE')pending.current=null;return false}pending.current=null;setView(result.value);setDirty(false);if(input.change.type==='create')setSelected(input.change.id);setMessage('Source protected in local recovery. Save the project file separately.');await onCommitted();return true}catch{setError('The source result is unknown. Retry the same source save.');return false}finally{setBusy(false)}
  }
  async function mutate(change:SourceChangeInput['change']):Promise<void>{if(!await save())return;setBusy(true);setError('');try{const result=await window.collie.changeSource({...scope(project),operationId:crypto.randomUUID(),change});if(result.ok){setView(result.value);if(change.type==='merge'){const target=result.value.sources.find(s=>s.id===change.targetId);if(target){setSelected(target.id);setDraft(target.metadata);setCreatorText(creators(target.metadata));setVerified(target.verified);setLinked(target.documentIds)}setMergeTarget('');setExportSelection(old=>old.filter(id=>id!==change.id))}if(change.type==='state'&&change.state==='trashed')setExportSelection(old=>old.filter(id=>id!==change.id));setMessage('Source change protected locally.');await onCommitted()}else setError(result.error.message)}finally{setBusy(false)}}
  async function pickImport():Promise<void>{if(!await save())return;setBusy(true);setError('');try{const pick=await window.collie.pickSourceImport(scope(project));if(!pick.ok){setError(pick.error.message);return}if(!pick.value)return;const result=await window.collie.previewSourceImport({...scope(project),token:pick.value.token});if(!result.ok){setError(result.error.message);return}pendingImport.current=null;setPreview(result.value);setChoices(result.value.rows.map(r=>({index:r.index,action:r.error||r.candidates.length?'skip' as const:'create' as const,targetId:null})));setMessage('Review every row. Similar titles are never merged automatically.')}finally{setBusy(false)}}
  async function commitPreview():Promise<void>{if(!preview)return;setBusy(true);setError('');pendingImport.current??=crypto.randomUUID();try{const result=await window.collie.commitSourceImport({...scope(project),operationId:pendingImport.current,token:preview.token,digest:preview.digest,choices});if(result.ok){pendingImport.current=null;setView(result.value);setPreview(null);setMessage('Bibliography imported. Review the retained report and unknown fields.');await onCommitted()}else{if(result.error.code!=='UNAVAILABLE')pendingImport.current=null;setError(result.error.message)}}finally{setBusy(false)}}
  async function attach(sourceId:string):Promise<void>{if(!await save())return;setBusy(true);setError('');setMessage('Copying the selected original into local managed storage…');try{const pick=await window.collie.pickSourceAttachment(scope(project));if(!pick.ok){setError(pick.error.message);return}if(!pick.value)return;const operationId=crypto.randomUUID();attachmentOperation.current=operationId;setAttachmentProgress(null);const result=await window.collie.attachSourceFile({...scope(project),operationId,sourceId,token:pick.value.token});if(result.ok){setView(result.value);setMessage('Managed copy attached. The selected external file is no longer needed for project backup.');await onCommitted()}else setError(result.error.message)}finally{attachmentOperation.current=null;setAttachmentProgress(null);setBusy(false)}}
  async function exportLibrary():Promise<void>{if(!await save())return;setBusy(true);setError('');try{const result=await window.collie.exportSources({...scope(project),operationId:crypto.randomUUID(),format:exportFormat,sourceIds:exportSelection});if(result.ok){setExportLosses(result.value.losses);setMessage(`Exported ${result.value.count} sources to ${result.value.path}. Review the declared losses below.`)}else if(result.error.code!=='CANCELLED')setError(result.error.message)}finally{setBusy(false)}}
  const current=view?.sources.find(s=>s.id===selected)
  const locked=disabled||busy
  const fieldsLocked=locked||!!pending.current
  const draftBinding = useRetainedDraft('sources', {
    read: () => ({scope:scope(project),kind:'source',entityId:selected,label:'source metadata',dirty:latest.current.dirty,
      composing:false,busy,pendingOperation:pending.current,policy:'flush',issue:error,
      target:{kind:'workspace',scope:scope(project),view:'research',target:{kind:'sources'}}}),
    flush:save,focus:()=>panel.current?.focus()
  })
  useRetainedDraft('source-operations', {
    read:()=>({scope:scope(project),kind:'source-operation',entityId:selected,label:'source import or attachment',dirty:false,
      composing:false,busy,pendingOperation:pendingImport.current,policy:'operation',issue:pendingImport.current?error:undefined,
      status:busy?'Working…':message||undefined,
      target:{kind:'workspace',scope:scope(project),view:'research',target:{kind:'sources'}}})
  })
  return <section ref={panel} tabIndex={-1} {...draftBinding} className="sources-panel" aria-labelledby="sources-title">
    <h2 id="sources-title">Sources and bibliography</h2>
    <p>Source metadata stays local. DOI and URL entries are identifiers only; Collie Writer does not look them up. Attachments become managed copies included in project backups.</p>
    <div className="project-actions"><button type="button" disabled={locked||readOnly||dirty} onClick={()=>choose(null)}>New source</button><button type="button" disabled={locked||readOnly||!!pendingImport.current} onClick={()=>void pickImport()}>Import CSL JSON, BibTeX or RIS…</button><label>Export format <select value={exportFormat} disabled={locked} onChange={e=>setExportFormat(e.target.value as BibliographyFormat)}><option value="csl-json">CSL JSON</option><option value="bibtex">BibTeX</option><option value="ris">RIS</option></select></label><button type="button" disabled={locked} onClick={()=>void exportLibrary()}>Export {exportSelection.length?'selected':'all active'} sources…</button></div>
    {preview?<details open><summary>Import preview · {preview.count} records</summary><p>Only reviewed choices commit. Invalid rows must be skipped; each duplicate candidate needs an explicit decision. Cancel leaves the library unchanged.</p><ol>{preview.rows.map(row=>{const choice=choices[row.index];return <li key={row.index}><strong>{row.metadata?.title||`Record ${row.index+1}`}</strong> · {row.metadata?.type||'invalid'} {row.error?<span role="alert">{row.error}</span>:null}{row.candidates.length?<p>Possible matches: {row.candidates.map(c=>`${view?.sources.find(s=>s.id===c.id)?.metadata.title||c.id} (${c.reason})`).join(', ')}</p>:null}{row.losses.length?<p>Omitted on export: {row.losses.join(' ')}</p>:null}<label>Action <select value={`${choice?.action||'skip'}:${choice?.targetId||''}`} disabled={locked||!!row.error||!!pendingImport.current} onChange={e=>{pendingImport.current=null;const [action,targetId]=e.target.value.split(':');setChoices(old=>old.map(c=>c.index===row.index?{...c,action:action as SourceImportChoice['action'],targetId:targetId||null}:c))}}><option value="skip:">Skip</option><option value="create:">Keep separate</option>{row.candidates.map(c=><option key={`merge-${c.id}`} value={`merge:${c.id}`}>Merge into {view?.sources.find(s=>s.id===c.id)?.metadata.title||c.id.slice(0,8)} · {c.reason}</option>)}{row.candidates.map(c=><option key={`link-${c.id}`} value={`link:${c.id}`}>Link imported ID to {view?.sources.find(s=>s.id===c.id)?.metadata.title||c.id.slice(0,8)} · {c.reason}</option>)}</select></label></li>})}</ol><div className="project-actions"><button disabled={locked||readOnly} onClick={()=>void commitPreview()}>Commit reviewed import</button><button disabled={locked||!!pendingImport.current} onClick={()=>{pendingImport.current=null;setPreview(null);setChoices([]);setMessage('Import cancelled. No source changed.')}}>Cancel import</button></div></details>:null}
    <h3>Library</h3><ul>{view?.sources.filter(s=>s.state!=='merged').map(source=><li key={source.id}><label><input type="checkbox" checked={exportSelection.includes(source.id)} disabled={locked||source.state!=='active'} onChange={e=>setExportSelection(old=>e.target.checked?[...old,source.id]:old.filter(id=>id!==source.id))} aria-label={`Select ${source.metadata.title} for export`} /></label> <button type="button" disabled={locked||dirty} onClick={()=>choose(source)}>{source.metadata.title}</button> · {source.metadata.type} · {source.verified?'verified':'unverified'}{source.state==='trashed'?' · trashed':''}</li>)}</ul>
    <form onSubmit={e=>{e.preventDefault();if(!readOnly)void save()}}><fieldset disabled={readOnly}><h3>{current?'Edit source':'New source'}</h3>
      <label>Work type <select value={draft.type} disabled={fieldsLocked} onChange={e=>change({...draft,type:e.target.value as SourceMetadata['type']})}>{SOURCE_TYPES.map(type=><option key={type} value={type}>{type}</option>)}</select></label>
      <label>Title <input required maxLength={2000} value={draft.title} disabled={fieldsLocked} onChange={e=>change({...draft,title:e.target.value})} /></label>
      <label>Creators (Family, Given; organization name without comma; separate with semicolons) <input value={creatorText} disabled={fieldsLocked} onChange={e=>change(draft,e.target.value)} /></label>
      <label>Issued date (YYYY, YYYY-MM or YYYY-MM-DD) <input value={draft.issued} disabled={fieldsLocked} onChange={e=>change({...draft,issued:e.target.value})} /></label>
      {([['containerTitle','Journal / book title'],['publisher','Publisher'],['edition','Edition'],['volume','Volume'],['issue','Issue'],['page','Pages'],['DOI','DOI'],['URL','URL'],['ISBN','ISBN'],['ISSN','ISSN']] as const).map(([field,label])=><label key={field}>{label} <input maxLength={2000} value={draft[field]} disabled={fieldsLocked} onChange={e=>change({...draft,[field]:e.target.value})} /></label>)}
      <label><input type="checkbox" checked={verified} disabled={fieldsLocked} onChange={e=>{setVerified(e.target.checked);setDirty(true);pending.current=null}} /> I manually verified this metadata</label>
      <fieldset><legend>Used in sections</legend>{project.documents.filter(d=>d.kind==='text').map(d=><label key={d.id}><input type="checkbox" checked={linked.includes(d.id)} disabled={fieldsLocked} onChange={e=>{setLinked(old=>e.target.checked?[...old,d.id]:old.filter(id=>id!==d.id));setDirty(true);pending.current=null}} /> {d.title}</label>)}</fieldset>
      <button type="submit" disabled={locked||!dirty}>{pending.current?'Retry source save':'Protect source locally'}</button>
    </fieldset></form>
    {current?<details><summary>Source history and attachments</summary><p>Source ID: {current.id}. Provenance: {current.provenance}. {current.verified?'Metadata manually verified.':'Metadata not manually verified.'}</p>{current.aliases.length?<p>Retained imported/merged IDs: {current.aliases.join(', ')}</p>:null}{current.rawImport?<details><summary>Original imported record</summary><pre>{current.rawImport}</pre></details>:null}{current.unknownFields.length?<p>Retained unknown fields: {current.unknownFields.join(', ')}</p>:null}
      <p>Trashing or merging a cited source leaves its manuscript citations visible but unresolved. Restore a trashed source or explicitly replace each affected citation in Citations and bibliography. Source and citation history are retained.</p>
      <div className="project-actions"><button disabled={locked||readOnly||dirty||current.state!=='active'} onClick={()=>void attach(current.id)}>Attach local original…</button><button disabled={locked||readOnly||dirty||current.state==='merged'} onClick={()=>void mutate({type:'state',id:current.id,expectedRevisionId:current.revisionId,state:current.state==='trashed'?'active':'trashed'})}>{current.state==='trashed'?'Restore source':'Move source to trash'}</button></div>
      <ul>{current.attachments.map(a=><li key={a.id}>{a.name} · {a.mediaType} · {Math.round(a.bytes/1024)} KB · {a.sha256.slice(0,12)} {a.state==='removed'?'(removed; retained for history)':''} {a.mediaType==='application/pdf'||a.mediaType==='text/plain'?<button disabled={locked||dirty} onClick={()=>onInspect(current.id)}>Inspect versions and excerpts</button>:null} {a.state==='active'?<><button disabled={locked} onClick={()=>void window.collie.exportSourceAttachment({...scope(project),attachmentId:a.id,suggestedName:a.name}).then(r=>{if(r.ok)setMessage(`Managed original copied to ${r.value.path}`);else if(r.error.code!=='CANCELLED')setError(r.error.message)})}>Save copy…</button><button disabled={locked||readOnly||dirty} onClick={()=>void mutate({type:'removeAttachment',id:current.id,attachmentId:a.id,expectedRevisionId:current.revisionId})}>Remove link</button></>:null}</li>)}</ul>
      <h4>Merge this source into another</h4><p>Its old ID and links remain as aliases. The target keeps its metadata; this source stays in retained history.</p><select aria-label="Merge target" disabled={locked||dirty} value={mergeTarget} onChange={e=>setMergeTarget(e.target.value)}><option value="">Choose target</option>{view?.sources.filter(s=>s.id!==current.id&&s.state==='active').map(s=><option key={s.id} value={s.id}>{s.metadata.title}</option>)}</select><button disabled={locked||readOnly||dirty||!mergeTarget} onClick={()=>void mutate({type:'merge',id:current.id,targetId:mergeTarget,expectedRevisionId:current.revisionId})}>Merge into target</button>
    </details>:null}
    {view?.reports.length?<details><summary>Import reports</summary>{view.reports.map(r=><div key={r.id}><h4>{r.format} · {new Date(r.createdAt).toLocaleString()}</h4><p>{r.imported} imported or linked; {r.skipped} skipped.</p>{r.errors.map((e,i)=><p key={i} role="alert">{e}</p>)}{r.losses.map((l,i)=><p key={i}>{l}</p>)}</div>)}</details>:null}
    {exportLosses.length?<details open><summary>Latest export: declared field losses</summary><ul>{exportLosses.map((loss,index)=><li key={index}>{loss}</li>)}</ul></details>:null}
    {attachmentProgress?<p role="status">Copying managed original: {Math.round(100*attachmentProgress.transferred/attachmentProgress.total)}% · {Math.round(attachmentProgress.transferred/1024)} of {Math.round(attachmentProgress.total/1024)} KiB</p>:null}
    {message?<p role="status">{message}</p>:null}{error?<p role="alert">{error}</p>:null}
  </section>
}
