const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char])
export function page(path, config) {
  const contact = `<a href="mailto:${escape(config.supportEmail)}">${escape(config.supportEmail)}</a>`
  const pages = {
    '/': ['Collie Writer nonfiction', '<p>Offline writing, source inspection, evidence organization, citations and exports. Untimed free use includes one editable personal project at a time, with unrestricted switching. Every project remains readable, exportable and recoverable.</p><p>United States base prices: $9.99 USD per month or $199 USD lifetime. Applicable taxes and the total appear before payment. Both offers add unlimited editable projects, named compilation recipes and multi-format batches. Lifetime includes all future updates to the nonfiction edition, with no major-version ceiling. No trial or automatic free-to-paid conversion.</p><p>Purchasing begins only from the desktop app when checkout has been enabled. No AI feature is being sold as currently available. Permanently ad-free.</p>'],
    '/edition': ['Edition and personal use', '<p>Direct nonfiction purchases cover your own Mac and Windows installations. There is no project-count limit for paid access and no device fingerprinting. A purchase recovery code connects a replacement computer; keep it private. Store purchases have separate restore routes.</p><p>Buying lifetime access does not automatically cancel an existing subscription. Use Manage subscription to review and cancel recurring billing if desired.</p><p>Cached lifetime grants work offline until an authentic revocation is received. Monthly access lasts through the verified paid period, with up to 14 days of signed renewal grace. Reading, exporting, backups and recovery remain available after access changes.</p>'],
    '/privacy': ['Purchase privacy', '<p>Manuscripts, research, source files, project identifiers, paths, content hashes, histories and backups are not sent to this service. Paddle handles the billing details you enter, payment processing and required transaction records.</p><p>This service stores opaque Paddle customer/purchase IDs, paid-access decisions, signing revisions, hashed recovery and connection credentials, and minimal webhook receipt records. Browser/app sessions expire after 20 minutes and are removed. Device connection credentials expire after one year unless refreshed. No analytics, advertising scripts, sponsored content or tracking pixels are added by Collie Writer.</p><p>Your browser contacts Paddle only when opening checkout or subscription management. Your desktop contacts this service only when you request a purchase, restore, status refresh or disconnect. Your own cloud storage remains your arrangement with that provider.</p><p>Purchase and revocation history is retained for restore and replay protection. Contact support about deletion and legally required retention. Do not attach writing or project files to a purchase support request.</p>'],
    '/refunds': ['Cancellations and refunds', `<p>Manage recurring billing through the subscription-management link in Collie Writer. Cancellation at period end preserves access already paid for. A pending payment or pending refund is not a completed transaction.</p><p>Contact ${contact} for a refund request or purchase problem. Paddle processes approved refunds under the applicable purchase terms and consumer rights. This page does not promise an additional unconditional refund period. Approved full refunds and chargebacks remove the affected paid period or lifetime grant when the app next refreshes. Partial refunds retain access unless their approved total fully refunds the transaction. Projects, exports and recovery remain yours.</p>`],
    '/support': ['Purchase support', `<p>Contact ${contact}. Give the purchase receipt/reference and a brief description of the billing issue. Never send a project, manuscript, source attachment, password, private signing key or complete recovery code.</p><p>Lost recovery codes require purchase-ownership verification through the merchant record. Support can replace a recovery code without moving or receiving your writing. Disconnect purchase account clears this computer's connection credentials; it does not cancel billing or erase cached signed licenses.</p>`],
    '/connect': ['Connect purchase access', '<p id="status" role="status">Reading the session started by Collie Writer…</p><p>This page cannot grant access from a browser success message. Collie Writer receives only service-verified, signed purchase decisions.</p><button id="buy" hidden>Open secure checkout</button><form id="restore" hidden><label>Purchase recovery code <input id="code" type="password" autocomplete="off" spellcheck="false" required maxlength="46"></label><button>Restore this purchase</button></form><button id="complete" hidden>Check payment and show recovery code</button><div id="recovery" hidden><p>Keep this code in your password manager. It restores this purchase on your own computers. A newly requested code replaces the previous recovery code.</p><label>Recovery code <input id="saved-code" readonly autocomplete="off"></label></div><p>Return to Collie Writer and choose Check completion after payment or restore. Closing this page does not cancel recurring billing.</p>']
  }
  const content = pages[path]
  if (!content) return null
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(content[0])}</title><link rel="stylesheet" href="/site.css"></head><body><header><a href="/">Collie Writer</a></header><main><h1>${escape(content[0])}</h1>${content[1]}</main><footer><nav aria-label="Purchase information"><a href="/edition">Edition</a> <a href="/privacy">Privacy</a> <a href="/refunds">Refunds</a> <a href="/support">Support</a></nav><p>Seller: ${escape(config.sellerName)}. ${config.environment === 'sandbox' ? 'Sandbox configuration. No live sale.' : 'United States · USD.'} Ad-free, always.</p></footer>${path === '/connect' ? '<script src="/connect.js" defer></script>' : ''}</body></html>`
}
